#!/bin/sh

# PROVIDE: shew_securelevel
# REQUIRE: LOGIN shew_xdm

# Add this to rc.conf to enable securelevel:
#   shew_securelevel_enable="YES"

. /etc/rc.subr

name='shew_securelevel'
rcvar="${name}_enable"
load_rc_config "${name}"

start_cmd='sleep 60 && /sbin/sysctl kern.securelevel=1 &'
	# There must be a sleep here, or securelevel will crash Xorg.

: ${shew_securelevel_enable='NO'}

run_rc_command "$1"
